import type { Metadata } from "next";
import { Tektur, Lexend_Deca } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sidebar";

const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
});

const lexend = Lexend_Deca({
  variable: "--font-lexend",
  subsets: ["latin"],
});

//todo: change description...
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`h-screen flex ${tektur.variable} ${lexend.variable} antialiased`}
      >
        <SideBar></SideBar>

        <main className="flex justify-center xl:items-center w-full text-coral py-12 overflow-y-auto h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
